---
name: build
on:
  push:
    branches-ignore:
      - 'main'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  go-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: '1.19'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  docker-build-and-ecr-push:
    runs-on: ubuntu-latest
    environment: waypoint
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: arn:aws:iam::%%aws_account_id%%:role/%%role_name%%
          role-session-name: githubactionssession
          aws-region: %%aws_region%%

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.6.0

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # ECR name must be lowercase
          ECR_REPOSITORY: %%wp_project_lower%%
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Install Waypoint CLI and set up context
        env:
          WAYPOINT_SERVER_ADDR: ${{ secrets.WAYPOINT_SERVER_ADDR }}
          WAYPOINT_SERVER_TOKEN: ${{ secrets.WAYPOINT_SERVER_TOKEN }}
        run: |
          # Install the latest Waypoint CLI
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install waypoint
          
          # Create a CLI context to hook up to a Waypoint server
          waypoint context create -server-addr="$WAYPOINT_SERVER_ADDR" -server-auth-token="$WAYPOINT_SERVER_TOKEN" -server-require-auth=true -server-platform="hcp" -set-default hcp-waypoint-gh-runner
          waypoint context verify

      # This step pulls the previously built Docker image, and wraps it in the Waypoint Entrypoint,
      # and pushes it back to the registry, to be used in dev deployments
      - name: Waypoint build in dev workspace
        run: |
          waypoint version
          waypoint build -workspace=dev -project=%%wp_project%% -app=%%wp_project%% -remote-source=ref=$GITHUB_SHA

      # This step refers to the app image wrapped in the Waypoint Entrypoint, to be used in prod deployments
      - name: Waypoint build in prod workspace
        run: |
          waypoint version
          waypoint build -workspace=prod -project=%%wp_project%% -app=%%wp_project%% -remote-source=ref=$GITHUB_SHA
