---
name: repo-init
on: workflow_dispatch

jobs:
  protobuf-generation:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.3

    - name: Set up Go
      uses: actions/setup-go@v4.0.1
      with:
        go-version: '1.19'
        
    - name: Install protoc-gen-go
      run: |
        go install github.com/golang/protobuf/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    # Install the `buf` CLI
    - name: Install buf
      uses: bufbuild/buf-setup-action@v1.21.0

    - name: Generate protos
      run: buf generate

    - name: Commit generated protobuf code
      run: |
        git config --global user.name 'GHA'
        git config --global user.email 'team-waypoint@users.noreply.github.com'
        git commit -am "proto: Generate protocol buffer code."
        git push
