---
name: repo-init
on: workflow_dispatch

jobs:
  protobuf-generation:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

    - name: Set up Go
      uses: actions/actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
      with:
        go-version: '1.19'
        
    - name: Install protoc-gen-go
      run: |
        go install github.com/golang/protobuf/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    # Install the `buf` CLI
    - name: Install buf
      uses: bufbuild/buf-setup-action@0b2634d023322ed4186879e9a60c01783a8963d4

    - name: Generate protos
      run: buf generate

    - name: Commit generated protobuf code
      run: |
        git config --global user.name 'GHA'
        git config --global user.email 'team-waypoint@users.noreply.github.com'
        git commit -am "proto: Generate protocol buffer code."
        git push
